### ISSUE TITLE
Type Results Return Questions

### ISSUE THREAD

**Issue by shinh09** [OSS-TeamProjectt/IT-MBTI#27]
Results page related questions! The way you calculate the results is simply the sum of your answers. By the way, if the sum results are the same, what type of results should you give? ㅠㅠ

**Comment by kimm00** [comment]
Why don't we use additional data for the same case? For example, add weight to a specific question or consider an additional priority question.

Like in UI/UX Designer, we can weight this question 'Enjoys solving problems with creative ideas.'
-> It's because the core of UI/UX design is creative problem solving and user-centered design.

**Comment by han3o1** [comment]
Great point to consider!
Instead of solely relying on weighted questions to resolve ties, how about giving users a choice in the process?

For instance, if multiple results have the same score, you could present an additional question like, "Which activity do you prefer more?" to help further differentiate the results. This approach could make the experience more interactive for the user and increase their trust in the final result.

By involving users in the decision-making process, it shifts from being purely calculation-based to feeling more personalized and engaging. Great work so far! 👍

**Comment by yuyoung924** [comment]
If the score is tied, I think  we'll have to think about what results to return. Let's put all those results on the results page so that users can check them. What do you think?

**Comment by eun5young** [comment]
I think this is a good idea!! As Yuyoung said, it would be a good idea to show the users all the results with the most points! Why don't we make it so that the users can turn the page and see the next results?

**Comment by shinh09** [comment]
> If the score is tied, I think we'll have to think about what results to return. Let's put all those results on the results page so that users can check them. What do you think?

I think this way too.. I think the user will like to show all the results that they might be interested in.

**Comment by han3o1** [comment]
I completely agree! Displaying all tied results on the results page would be a great way to ensure users can see all their top matches. This approach feels fair and user-friendly. Then, let's move forward with this idea!

**Comment by kimm00** [comment]
I agree that showing all tied results on the results page, along with the ability to navigate through them, would make the experience more engaging and user-friendly. Let's proceed with implementing this idea, and we can refine it further if needed during the process. Great teamwork, everyone!
