### ISSUE TITLE
Percentage Calculation Bug on Result Page 

### ISSUE THREAD

**Issue by kimm00** [OSS-TeamProjectt/IT-MBTI#69]
In the current code, when calculating the total score, the percentage of each type of score is incorrect when calculating the percentage ㅠㅠ
This results in an error where if all the questions were answered neutral, the total should be 50% but **60%** is output. What should we can do??

**Comment by han3o1** [comment]
You are absolutely right! The issue likely occurs because the current scoring system assigns fixed integer values (1, 2, 3, 4, 5) to each option, and the percentage calculation doesn't properly normalize the scores, leading to inflated percentages when all responses are neutral.

A possible solution could be to adjust the scoring system to use scaled values like 0, 2.5, 5, 7.5, 10 instead of 1, 2, 3, 4, 5. This would allow for a more accurate calculation of the total percentage, ensuring that neutral responses (e.g., 5 when scaled) contribute proportionately to the final result. By using this method, if all responses are neutral, the total percentage would correctly reflect 50%, avoiding the current overestimation issue.

Would love to hear your thoughts on this approach! 😊

**Comment by kimm00** [comment]
Aha!!! Very good approach! I will revise the code to reflect Haneol's comments. Thank you very much:) ☺️

**Comment by kimm00** [comment]
It still works strangely... We need to check it more detailed. ㅜㅜ
